GitHub Actionsエラー解消

diff --git a/.github/workflows/qiita_sync.yml b/.github/workflows/qiita_sync.yml
--- a/.github/workflows/qiita_sync.yml
+++ b/.github/workflows/qiita_sync.yml
@@ -6,6 +6,9 @@ on:
       - main
   workflow_dispatch:
 
+env:
+  QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}
+
 jobs:
   qiita_sync_check:
     name: Run qiita-sync sync
@@ -28,15 +31,32 @@ jobs:
 
       - name: Git
         run: |
-          find . -name '*.md' -not -path './.*' | xargs git add
-          if ! git diff --staged --exit-code --quiet
-          then
-            git config user.name github-actions
-            git config user.email github-actions@github.com
-            find . -name '*.md' -not -path './.*' | xargs git add
-            git commit -m "updated by qiita-sync"
-            git remote set-url origin https://${{ env.GITHUB_TOKEN }}@github.com/kojikawazu/qiita-article-kk.git
-            git push
+          FILES_CHANGED=$(git diff --name-only HEAD^ HEAD | wc -l)
+          if [ "$FILES_CHANGED" -ne 1 ]; then
+            echo "Error: More than one file changed in the last commit."
+            exit 1
           fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        
+          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
+          for ARTICLE_PATH in $CHANGED_FILES; do
+
+            ARTICLE_CONTENT=$(cat $ARTICLE_PATH)
+            TARGET_TITLE=$(head -n 1 $ARTICLE_PATH | sed 's/^# //')
+
+            ARTICLES=$(curl -s "https://qiita.com/api/v2/users/${{ env.QIITA_USER_ID }}/items" -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}")
+            ARTICLE_ID=$(echo $ARTICLES | jq -r ".[] | select(.title == \"$TARGET_TITLE\") | .id")
+        
+            if [ ! -z "$ARTICLE_ID" ]; then
+              curl -X PATCH "https://qiita.com/api/v2/items/ARTICLE_ID" \
+                -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}" \
+                -H "Content-Type: application/json" \
+                -d "{\"body\": \"$ARTICLE_CONTENT\"}"
+            else
+              RESPONSE=$(curl -X POST "https://qiita.com/api/v2/items" \
+                -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}" \
+                -H "Content-Type: application/json" \
+                -d "{\"body\": \"$ARTICLE_CONTENT\", \"title\": \"Your Title\", \"tags\": [{\"name\": \"sample\"}]}")
+              ARTICLE_ID=$(echo $RESPONSE | jq '.id')
+            fi
+        shell: bash
+        
